# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-04 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='created_at',
            field=models.CharField(default=1525403925.1714058, max_length=50),
        ),
        migrations.AlterField(
            model_name='raider',
            name='thumbnail',
            field=models.ImageField(upload_to='cover/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='avatar/'),
        ),
    ]
