# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-04 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20180504_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='created_at',
            field=models.CharField(default=1525404041.4514856, max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='raider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
