# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-04 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_auto_20180504_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='raider',
            name='uid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='attention',
            name='other_uid',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='attention',
            name='uid',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='code',
            name='created_at',
            field=models.CharField(default=1525410898.165739, max_length=50),
        ),
        migrations.AlterField(
            model_name='collection',
            name='rid',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='collection',
            name='uid',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rid',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='uid',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='praise',
            name='comment_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='praise',
            name='uid',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='raider',
            name='like_counts',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='raider',
            name='play_counts',
            field=models.IntegerField(null=True),
        ),
    ]
