# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-04 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_auto_20180504_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raider',
            name='user',
        ),
        migrations.AlterField(
            model_name='code',
            name='created_at',
            field=models.CharField(default=1525412604.6489935, max_length=50),
        ),
    ]
