# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-04 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_auto_20180504_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='created_at',
            field=models.CharField(default=1525416947.3665159, max_length=50),
        ),
        migrations.AlterField(
            model_name='raider',
            name='thumbnail',
            field=models.ImageField(upload_to='cover/%Y/%m/%d'),
        ),
    ]
