# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-06 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_auto_20180504_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('reply_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_id', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('from_uid', models.CharField(max_length=200)),
                ('reply_type', models.CharField(max_length=20)),
                ('p_reply_id', models.CharField(max_length=200)),
                ('to_uid', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'reply',
            },
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='uid',
            new_name='from_uid',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='raider',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply',
        ),
        migrations.AlterField(
            model_name='code',
            name='created_at',
            field=models.CharField(default=1525599991.5192423, max_length=50),
        ),
    ]
