# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-07 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_auto_20180507_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='created_at',
            field=models.CharField(default=1525663921.1325471, max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='like_counts',
            field=models.IntegerField(default='0'),
        ),
    ]
