# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-10 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_auto_20180507_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='PraiseReply',
            fields=[
                ('praise_reply_id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=200)),
                ('reply_id', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'praise_reply',
            },
        ),
        migrations.AlterField(
            model_name='code',
            name='created_at',
            field=models.CharField(default=1525935620.6871457, max_length=50),
        ),
    ]
