# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-11 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_auto_20180510_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='created_at',
            field=models.CharField(default=1526030094.8966806, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='avatar/%Y/%m/%d'),
        ),
    ]
