# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-14 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0014_auto_20180511_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='created_at',
            field=models.CharField(default=1526276126.5052779, max_length=50),
        ),
    ]
