# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-18 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0015_auto_20180514_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='raider',
            name='city',
            field=models.CharField(default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='raider',
            name='country',
            field=models.CharField(default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='raider',
            name='province',
            field=models.CharField(default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='code',
            name='created_at',
            field=models.CharField(default=1526632176.4442377, max_length=50),
        ),
        migrations.AlterField(
            model_name='raider',
            name='thumbnail',
            field=models.ImageField(default='cover/no_thumbnail.jpeg', upload_to='cover/%Y/%m/%d'),
        ),
    ]
